import type { Topic } from './types.ts';

/** Saludos y conversación: las tarjetas son Buddy haciendo cada saludo; las preguntas van en "Say it!". */
export default {
  id: 'hello',
  title: 'Hello!',
  sayTitle: 'Hello, hello!',
  icon: '👋',
  words: [
    {
      id: 'hello',
      image: '👋',
      say: 'Hello.',
      ask: 'Find hello!',
      facts: ['Hello, Buddy!', 'Hello! How are you?'],
      sounds: ['hallo', 'jelou', 'helo'],
      picture: 'standing at an open front door, waving one paw hello with a big smile',
    },
    {
      id: 'goodbye',
      image: '🚌',
      say: 'Goodbye.',
      ask: 'Find goodbye!',
      facts: ['Goodbye, Buddy!', 'Goodbye! See you later!'],
      sounds: ['good bye', 'bye bye', 'bye'],
      picture: 'walking away with a small backpack, looking back over his shoulder and waving goodbye',
    },
    {
      id: 'good-morning',
      image: '🌅',
      say: 'Good morning.',
      ask: 'Find good morning!',
      facts: ['Good morning, Emma!', 'Good morning! Time to wake up!'],
      picture: 'waking up and stretching happily in a small bed, with a big smiling rising sun in the window',
    },
    {
      id: 'good-night',
      image: '🌙',
      say: 'Good night.',
      ask: 'Find good night!',
      facts: ['Good night, Mom!', 'Good night! Sleep well.'],
      picture: 'tucked in a small bed under a blanket, eyes closing, with a crescent moon and stars in the window',
    },
    {
      id: 'thank-you',
      image: '🎁',
      say: 'Thank you.',
      ask: 'Find thank you!',
      facts: ['Thank you, Buddy!', 'Thank you very much!'],
      sounds: ['thanks', 'tank you', 'sank you'],
      picture: 'happily hugging a wrapped gift box with a big bow',
    },
    {
      id: 'please',
      image: '🙏',
      say: 'Please.',
      ask: 'Find please!',
      facts: ['Water, please!', 'Can I play, please?'],
      sounds: ['plis', 'pliz'],
      picture: 'sitting and asking nicely, both front paws pressed together, big hopeful eyes',
    },
  ],
  questions: [
    {
      id: 'name',
      image: '🙋‍♀️',
      ask: "What's your name?",
      answer: 'My name is Emma.',
      accepts: { kind: 'words', words: ['emma', 'ema', 'enma', 'emmy'] },
      picture: 'a cheerful little girl about 5 years old with brown hair and a pink bow, pointing at herself and smiling',
    },
    {
      id: 'age',
      image: '🎂',
      ask: 'How old are you?',
      answer: 'I am five.',
      accepts: { kind: 'number' },
      picture: 'a birthday cake with exactly five lit candles',
    },
    {
      id: 'from',
      image: '🇨🇴',
      ask: 'Where are you from?',
      answer: 'I am from Colombia.',
      accepts: { kind: 'words', words: ['colombia', 'columbia', 'colombian'] },
      picture: 'a small round globe showing South America with a cute map pin and a little flag with yellow, blue and red horizontal stripes',
    },
    {
      id: 'how-are-you',
      image: '😊',
      ask: 'How are you?',
      answer: 'I am happy!',
      accepts: { kind: 'topic', topicId: 'feelings', extra: ['fine', 'good', 'great', 'ok', 'okay', 'well', 'super'] },
      picture: 'a big round smiling sun face with a little heart',
    },
    {
      id: 'favorite-color',
      image: '🎨',
      ask: "What's your favorite color?",
      answer: 'My favorite color is pink.',
      accepts: { kind: 'topic', topicId: 'colors', extra: ['purple', 'white', 'black', 'brown'] },
      picture: "a painter's palette with six bright paint colors and a brush",
    },
    {
      id: 'like-apples',
      image: '🍎',
      imageName: 'word-food-apple',
      ask: 'Do you like apples?',
      answer: 'Yes, I do!',
      accepts: { kind: 'yesno' },
    },
    {
      id: 'like-dogs',
      image: '🐶',
      imageName: 'word-animals-dog',
      ask: 'Do you like dogs?',
      answer: 'Yes, I do!',
      accepts: { kind: 'yesno' },
    },
  ],
  homeMission: ['Good morning!', 'Thank you! / Please!', "What's your name? How old are you?"],
} satisfies Topic;
